### ISSUE TITLE
Invalid request body

### ISSUE THREAD

**Issue by dra-ramdan-aziz** [mustofa-id/satusehat-kyc#1]
Maaf, izin bertanya, saya sudah mengikuti arahan dari halaman utama. Lalu ketika saya buka aplikasi nya, hanya tampil tulisan Invalid BodyRequest. Mohon bantuan nya. Terima Kasih sebelumnya.
![image](https://github.com/mustofa-id/satusehat-kyc/assets/22186064/966e66bd-87ef-45ce-a132-f7dca1069ed0)

**Comment by mustofa-id** [comment]
Pake Nodejs versi berapa Pak?
Apakah niliai `ORIGIN ` di file `.env` sudah diatur?

**Comment by dra-ramdan-aziz** [comment]
Alhamdulillah sudah bisa pa. Enggak tau kenapa, hari ini saya coba lagi langsung bisa. nodeJS v.20.15. .env sudah diatur. Kemaren saya pake client secret Staging. Saya ubah pakai client secret production sudah bisa jalan. Ijin pakai aplikasi nya pa. Terima Kasih sebelumnya.

**Comment by mustofa-id** [comment]
Alhamdulillah. KYC hanya tersedia di mode Production Pak.
Silakan Pak, aplikasi dapat digunakan secara bebas.
